// lib/db/db_repository.dart (moved from lib/data)

import 'package:drift/drift.dart';
import 'app_db.dart';
import 'csv_io.dart';
import 'dart:async';

class DbRepository {
  final AppDb db;
  // A simple broadcast stream to notify listeners about changes (items/sales).
  final StreamController<String> _changes = StreamController<String>.broadcast();

  DbRepository(this.db);

  Stream<String> get changes => _changes.stream;

  // Items helpers
  Future<List<Item>> fetchItems() => db.getAllItems();
  
  // Update an item record and emit a change notification.
  Future<bool> updateItem(Item item) async {
    final res = await db.updateItemData(item);
    _changes.add('item_updated');
    return res;
  }
  Future<int> addItem({required String name, String? category, int stock = 0, DateTime? lastUpdated, String? status}) {
    final companion = ItemsCompanion.insert(
      name: name,
      category: Value(category),
      stock: Value(stock),
      lastUpdated: Value(lastUpdated),
      status: Value(status),
    );
  final future = db.insertItem(companion);
  future.then((_) => _changes.add('item_added'));
  return future;
  }

  /// Delete an item by id and notify listeners.
  Future<int> deleteItemById(int id) async {
    final res = await db.deleteItemById(id);
    _changes.add('item_deleted');
    return res;
  }

  /// Export items to CSV file under lib/data/exports and return the file path.
  Future<String> exportItemsCsv() => exportItemsToCsvFile(db);

  /// Return CSV content for items as string (UI can show a save dialog).
  Future<String> exportItemsCsvString() => exportItemsToCsvString(db);

  /// Import items from a CSV string; returns number of rows inserted.
  Future<int> importItemsCsv(String csv) async {
    final count = await importItemsFromCsvString(db, csv);
    if (count > 0) _changes.add('item_imported');
    return count;
  }

  // Members helpers
  Future<List<Member>> fetchMembers() => db.getAllMembers();
  Future<int> addMember({String? lastName, String? firstName, String? middleName, String? role, String? contactNo, String? birthday, String? address, String? referrer, int points = 0}) {
    final companion = MembersCompanion.insert(
      lastName: Value(lastName),
      firstName: Value(firstName),
      middleName: Value(middleName),
      role: Value(role),
      contactNo: Value(contactNo),
      birthday: Value(birthday),
      address: Value(address),
      referrer: Value(referrer),
      points: Value(points),
      // QR intentionally not set here; QR is no longer generated by the UI.
    );
  final future = db.insertMember(companion);
  future.then((_) => _changes.add('member_added'));
  return future;
  }

  /// Export members to CSV file and return path.
  Future<String> exportMembersCsv() => exportMembersToCsvFile(db);

  /// Return CSV content for members as string (UI can show a save dialog).
  Future<String> exportMembersCsvString() => exportMembersToCsvString(db);

  /// Import members from CSV string, return inserted count.
  Future<int> importMembersCsv(String csv) async {
    final count = await importMembersFromCsvString(db, csv);
    if (count > 0) _changes.add('member_imported');
    return count;
  }

  // Sales CSV helpers
  /// Export sales to CSV file and return the file path.
  Future<String> exportSalesCsv() => exportSalesToCsvFile(db);

  /// Return CSV content for sales as string (UI can show a save dialog).
  Future<String> exportSalesCsvString() => exportSalesToCsvString(db);

  /// Import sales from CSV string; returns number of rows inserted.
  Future<int> importSalesCsv(String csv) async {
    final count = await importSalesFromCsvString(db, csv);
    if (count > 0) _changes.add('sale_imported');
    return count;
  }

  // Sales helpers
  Future<int> addSale({required int itemId, required String itemName, required int quantity, int price = 0}) {
    final companion = SalesCompanion.insert(
      itemId: itemId,
      itemName: itemName,
      quantity: quantity,
      price: Value(price),
    );
  final id = db.insertSale(companion);
  // notify listeners that a sale was added
  _changes.add('sale_added');
  return id;
  }

  Future<List<Sale>> fetchSales() => db.getAllSales();

  Future<List<Sale>> fetchSalesBetween(DateTime start, DateTime end) => db.getSalesBetween(start, end);

  /// Delete a sale by id and notify listeners.
  Future<int> deleteSaleById(int id) async {
    // Delete the requested sale.
    final res = await (db.delete(db.sales)..where((t) => t.id.equals(id))).go();
    if (res > 0) {
      try {
        // Renumber remaining sales so IDs stay contiguous (decrement ids > deleted id).
        // Note: updating primary keys is unusual; we do this because the UI desires contiguous IDs.
        await db.customStatement('UPDATE sales SET id = id - 1 WHERE id > ?;', [id]);

        // Update sqlite_sequence so AUTOINCREMENT continues from current max(id).
        await db.customStatement("UPDATE sqlite_sequence SET seq = (SELECT COALESCE(MAX(id),0) FROM sales) WHERE name = 'sales';");
      } catch (e) {
        // ignore errors from sqlite_sequence or custom statements
        // ignore: avoid_print
        print('Renumber sales after delete failed: $e');
      }

      _changes.add('sale_deleted');
    }
    return res;
  }

  /// Update a sale record and notify listeners.
  Future<bool> updateSale(Sale sale) async {
    final res = await db.update(db.sales).replace(sale);
    _changes.add('sale_updated');
    return res;
  }

  /// Clear all data from sales, items, and members tables.
  /// Emits delete notifications so UI can refresh.
  Future<void> clearAllData() async {
    try {
      await db.transaction(() async {
        await db.delete(db.sales).go();
        await db.delete(db.items).go();
        await db.delete(db.members).go();
        // Reset autoincrement sequences if present
        try {
          await db.customStatement("DELETE FROM sqlite_sequence WHERE name IN ('sales','items','members');");
        } catch (_) {
          // ignore if sqlite_sequence doesn't exist or fails
        }
      });

      // Notify listeners so UI can reload
      _changes.add('sale_deleted');
      _changes.add('item_deleted');
      _changes.add('member_deleted');
      _changes.add('db_cleared');
    } catch (e) {
      // ignore: avoid_print
      print('clearAllData failed: $e');
      rethrow;
    }
  }
}
